# valores por defecto para el parseo de argumentos
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8080
DEFAULT_SERVER_ALMACENAMIENTO = "data/servidor"
DEFAULT_CLIENT_DIR_DESCARGAS = "data/cliente/descargas"

# Protocol types
PROTO_SW = 0
PROTO_SACK = 1
PROTO_DIRECTO = 2
PROTOCOLS = {"sw": PROTO_SW, "sack": PROTO_SACK, "directo": PROTO_DIRECTO}

# Presupuesto de bytes: datagrama UDP > segmento > mensaje > bloque.
TAMANIO_MAX_DATAGRAMA = 1400
TAMANIO_CABECERA_SEGMENTO = 12
TAMANIO_CABECERA_MENSAJE = 3
TAMANIO_MAX_CARGA_SEGMENTO = TAMANIO_MAX_DATAGRAMA - TAMANIO_CABECERA_SEGMENTO
TAMANIO_BLOQUE = TAMANIO_MAX_CARGA_SEGMENTO - TAMANIO_CABECERA_MENSAJE

# Tiempos de infraestructura. Los futuros canales confiables definirán su RTO.
TIMEOUT_INACTIVIDAD_SESION = 5
TIMEOUT_DESPACHADOR = 0.2

# Recursos del servidor concurrente.
TAMANIO_BUFFER_RECEPCION_UDP = 8 * 1024 * 1024
CAPACIDAD_COLA_SESION = 4096
MAXIMO_SESIONES = 50
